export const USER_SIGN_IN_STARTED = 'USER_SIGN_IN_STARTED';
export const USER_SIGN_IN_SUCCEEDED = 'USER_SIGN_IN_SUCCEEDED';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const GET_ALL_USERS_STARTED = 'GET_ALL_USERS_STARTED';
export const GET_ALL_USERS_SUCCEEDED = 'GET_ALL_USERS_SUCCEEDED';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

